/**
 * Where a record came from. Every write that flows through the
 * MCP-operations layer must tag itself with one of these values so the
 * audit trail can distinguish a hand-entered row from an AI-assisted
 * one.
 */
export const AUDIT_SOURCES = [
  "manual",
  "ai_assisted",
  "screenshot_import",
  "mcp_operation",
  "system",
] as const;

export type AuditSource = (typeof AUDIT_SOURCES)[number];

export const AUDIT_SOURCE_LABELS: Record<AuditSource, string> = {
  manual: "Manual",
  ai_assisted: "AI-assisted",
  screenshot_import: "Screenshot import",
  mcp_operation: "MCP operation",
  system: "System",
};

export const AUDIT_SOURCE_HINTS: Record<AuditSource, string> = {
  manual: "Entered by hand. No AI involvement.",
  ai_assisted: "Generated by AI from a human prompt and reviewed before save.",
  screenshot_import:
    "Extracted from a screenshot via the import assistant. Pending review.",
  mcp_operation: "Created through an MCP-driven operation (admin/dev path).",
  system: "Created by Signal's own bootstrap/cleanup logic.",
};

export function isAuditSource(value: string): value is AuditSource {
  return (AUDIT_SOURCES as readonly string[]).includes(value);
}
